services:
  - type: web 
    plan: free
    name: esgi-node-app
    runtime: node
    region: frankfurt
    repo: https://github.com/Tristangle/render
    buildCommand: "npm install"
    startCommand: "npm run start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: esgi-node-app-db
          property: connectionString

databases:
  - name: esgi-node-app-db
    plan: free
    region: frankfurt