services:
  - type: web 
    plan: free
    name: esgi-node-app
    runtime: node
    repo: https://github.com/Tristangle/render
    buildCommand: ""
    startCommand: "node app.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: esgi-node-app-db
          property: connectionString

databases:
  - name: esgi-node-app-db
    plan: free